apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: platform-tools
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: 'https://github.com/la-belle-femme/250924-ticket-532-Deploy-Metrics-Server-via-ArgoCD-and-kustomize'
    path: 'TOOLS/platforms-tools/metric-server'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
